### ISSUE TITLE
Nginx Error - Client Prematurely Closed Connection during Content Comparison

### ISSUE THREAD

**Issue by johe123qwe** [meso-cacase/difff#2]
I am encountering an issue with my Nginx setup while using it as a proxy for a content comparison project. When attempting to compare a large amount of content, I am receiving the following error in the Nginx error log:

2023/12/26 17:49:44 [info] 1084292#1084292: *35318 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 192.168.1.4, server: diff.example.com, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "diff.example.com", referrer: "https://diff.example.com/"

This error is resulting in a browser response code of 524, and as a consequence, I am unable to obtain the content comparison results.

Environment:

- Operating System: Ubuntu 22.04
- Nginx Version: 1.24

I am seeking assistance in understanding and resolving this Nginx error to ensure smooth operation of the content comparison project. Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by meso-cacase** [comment]
Error 524 is a timeout error that occurs when the response time is too long. To avoid this, the following might help:

- If possible, extend the timeout setting.
- Reduce the response time by:
  - Shortening the input text.
  - Avoiding parallel processing.

Thanks!
